### ISSUE TITLE
Embargo / Access Conditions appear draggable/reorderable, but they are not.

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1504]
**Describe the bug**
This bug was discovered while reviewing #1475.  It affects both the *Bitstream* and *Item* Embargo/Access Conditions forms in the Submission UI.

**To Reproduce**

1. To reproduce on the *Bitstream* access conditions form:
    * Create a new submission.
    * Upload a Bitstream
    * Click "Edit" on that Bitstream/file.
    * Hover over the "Access Condition type" field, and you'll see the drag & drop handles appear.
2.  To reproduce on the *Item* access conditions form:
    * On the backend, make sure the `<step id="itemAccessConditions"/>` is enabled in your `item-submission.xml`. This enables the "Item access conditions" section
    * Create a new submission.
    * In the "Item access conditions" section of the form, hover over the "Access Condition type" field, and you'll see the drag & drop handles appear.

When you hover over an Access Condition type, the drag & drop handles appear. However, these access conditions cannot be reordered or dragged at this time. Here's a screenshot...notice the upper left corner shows the drag & drop handle/button.
![draggable](https://user-images.githubusercontent.com/483997/151407002-b3d9c4d0-4241-4b0c-b295-4ce69f682e85.png)

**Expected behavior**
Either these drag & drop handles should work (allowing you to reorder the access conditions).  Or, they should be removed.

**Comment by tdonohue** [comment]
Closing, as this appears to have been fixed.  I don't recall where, but it's no longer reproducible in 7.3

**Comment by MMilosz** [comment]
@tdonohue I think this issue may need to be reopened. While testing in sandbox.dspace.org, I found that the drag handles on the _Bitstream_ access conditions form **still appear** but don't actually allow reordering (see attached video).

The drag handles on the _Item_ access conditions form **work fine**.

Reproduction steps remain the same.

https://github.com/user-attachments/assets/8a91df54-9a6c-4d59-bdd4-14693ee185b1

Additional observations:
- dragging these handles can trigger the issue described in DSpace/dspace-angular#1268
