### ISSUE TITLE
Triple clicking in the text field of a onebox popup can return an "undefined" value

### ISSUE THREAD

**Issue by alanorth** [DSpace/dspace-angular#2621]
**Describe the bug**
In DSpace 7.6, if you have an input field of type `onebox` that uses a controlled vocabulary, if you **triple click** in the input field with nothing selected, the modal is dismissed and an `undefined` value is filled. I have entities disabled and this seems to affect any input field using a onebox with a controlled vocabulary.

**To Reproduce**
1. Configure `submission-forms.xml` with an input field of type `onebox` that is backed by a controlled vocabulary. For example:

```xml
            <row>
                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>subject</dc-element>
                    <dc-qualifier></dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Subject</label>
                    <vocabulary>srsc</vocabulary>
                    <input-type>onebox</input-type>
                    <required></required>
                </field>
            </row>
```

2. Click the text field to bring up the vocabulary select popup modal
3. Click three times in the empty text box

The browser console shows an error `TypeError: can't access property "isSelected"...`

**Expected behavior**
Nothing should happen.

**Comment by guillermo-escire** [comment]
Hi @tdonohue, I'm a partner at @jtimal, could you please assign me this issue to work on?

**Comment by guillermo-escire** [comment]
Hi @tdonohue, just following up on my previous comment—I'd be happy to take this issue on. Could you please assign it to me when you get a chance? Thanks!

**Comment by tdonohue** [comment]
@guillermo-escire : I'll assign this to you, but please verify this bug still exists. This ticket is over 2 years old and it's unclear to me if it still exists.

**Comment by guillermo-escire** [comment]
Thanks, @tdonohue ! I’ll first verify whether this bug still exists in the current version before proceeding.

**Comment by guillermo-escire** [comment]
Hi @tdonohue , I tested this on the current version and I can no longer reproduce the problem. Triple-clicking on a box entry no longer dismisses the modal or inserts an undefined value. It seems this bug has been fixed, so I think it's workable.

**Comment by tdonohue** [comment]
Thanks @guillermo-escire for checking if this bug still exists.  Since it sounds like it's fixed, I'm closing the ticket as "fixed".

If anyone finds (in the future) that this is still an issue, we can always reopen it at a later time.

**Comment by alanorth** [comment]
Good morning. I just tested this on `main` and the bug still exists. @guillermo-escire did you try with an input type of onebox?
