### ISSUE TITLE
Infinite load times on "My DSpace"

### ISSUE THREAD

**Issue by pnbecker** [DSpace/dspace-angular#3697]
## Describe the bug
We get user reports of infinite load times on "my DSpace". From what we hear this happens more likely if you finished one or multiple submissions without reloading the page in between. I tried to reproduce this on demo.dspace.org. So far I was able to reproduce it once when playing around with the workflow task filters. Unfortunately I have no clear path to reproduce it.

If you read this issue, did you run into the same problem? Can you describe what you did before? Are you a developer and did spot some code in my dspace that you thing might be the cause of this?

This is related to #3677

**Comment by kshepherd** [comment]
one question i have while digging around code that parses submission objects/data from the my dspace page -- what is the purpose of these `deepClone` calls?

```
  parse(request: RestRequest, data: RawRestResponse): ParsedResponse {
    this.dsoParser.parse(deepClone(request), deepClone(data));
    if (isNotEmpty(data.payload)
      && isNotEmpty(data.payload._links)
      && this.isSuccessStatus(data.statusCode)) {
      const dataDefinition = this.processResponse<SubmissionObject | ConfigObject>(data.payload, request);
      return new ParsedResponse(data.statusCode, undefined, { dataDefinition });
    } else if (isEmpty(data.payload) && this.isSuccessStatus(data.statusCode)) {
      return new ParsedResponse(data.statusCode);
    } else {
      throw new Error('Unexpected response from server');
    }
  }
```

**Comment by kanasznagyzoltan** [comment]
I have a similar problem in DSpace 8.0, if i have created a new submission, right after the new submission if a click on Editing the new item i immediately getting an infinite load error.

![dspace_crash_after_editing_a_new_submission_1](https://github.com/user-attachments/assets/74aa1725-20cb-4907-bfa0-688c8872b093)
![dspace_crash_after_editing_a_new_submission_2](https://github.com/user-attachments/assets/e3474c54-7c92-4e1e-aa86-3827de9bc383)
![dspace_crash_after_editing_a_new_submission_3](https://github.com/user-attachments/assets/569806d8-4fe6-4e67-8867-b3f44e35f477)
![dspace_crash_after_editing_a_new_submission_4](https://github.com/user-attachments/assets/f2cf946a-f168-4840-974d-fb9de915ec1a)

Could the related PR (https://github.com/DSpace/dspace-angular/pull/3677) also solve my issue? (That PR has 1 approval and 1 pending reviewer maybe it is close to happiness :))

Thank you for the info!

**Comment by alexandrevryghem** [comment]
@kanasznagyzoltan : Yes that bug should be resolved with #3677

**Comment by mirkoscherf** [comment]
We are facing the problem frequently when trying to deposit a new submission in 7.6.2. I've manually ported the changes from  #3716 but the problem still occurs

**Comment by jlipka** [comment]
@pnbecker Here is another small fix (at least for us) which leads to the described behaviour under specific circumstances - take a look at https://github.com/DSpace/dspace-angular/pull/5076 - there's also a video showing the bug.
