### ISSUE TITLE
e2e tests are not working due to config problem with the docker backend

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#498]
As noted on #495. Currently the docker backend that is used when travis runs e2e tests for the UI doesn't have its `dspace.restUrl` config param set. As a consequence that backend doesn't actually work. It will return [a 404](https://travis-ci.org/DSpace/dspace-angular/jobs/597514899#L5505) for every call. We hadn't noticed before because the current e2e tests didn't check anything that should have come from the server. 

It did surface this time, because #495 requires the site object to be retrieved from rest before the home page can track a view statistic, and therefore successfully render.

The issue needs to be fixed either by adding `dspace.restUrl` to `local.cfg` in the rest repo , or in the docker config.

In the mean time I'll create another PR to disable the e2e tests again, to prevent PRs being falsely flagged as broken by travis.

**Comment by tdonohue** [comment]
@artlowel : Rather than disabling the `e2e` tests, it seems simple enough (to me) to just add the `dspace.restUrl` to the docker `local.cfg` in these two places:

* https://github.com/DSpace/DSpace/blob/master/dspace/src/main/docker/local.cfg  (This is the default local.cfg for Docker images)
* https://github.com/DSpace/DSpace/blob/master/dspace/src/main/docker-compose/local.cfg (This is the local override when you run docker compose)

Likely just the former is the problem, but we should modify this in both places just for clarify.  Apologies that I haven't had a chance to look at this again until now, but I think that's the fix you are looking for.

**Comment by tdonohue** [comment]
@artlowel : I believe this has been fixed by https://github.com/DSpace/DSpace/pull/2554 (which has been merged, and Docker images have finished rebuilding).  Please recheck `e2e` tests.

**Comment by artlowel** [comment]
@tdonohue I restarted the build on @antoine-atmire's PR. He rolled back the commit that disabled the e2e tests. But the tests still fail, and you can [see in the log](https://travis-ci.org/DSpace/dspace-angular/jobs/599515885#L5482) that the path used by the server is still `http://localhost:8080/api` rather than `http://localhost:8080/server/api`

**Comment by tdonohue** [comment]
@artlowel : thanks for that note.  I've solve the issue in PR #500 (which passed all Travis tests, including e2e). So, this should now be solved.
