### ISSUE TITLE
Deposit of a submission doesn't work

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#622]
Deposit of a submission doesn't work due to a full projection issue. Full projection option is used on post to workflowitem endpoint, this cause an error when parsing response because it tries to set `workflowactions` property to a null object. 

A solution should be to disable full projection option when depositing a submission

**Comment by tdonohue** [comment]
@atarix83 : As mentioned in #623, I'm not able to reproduce this error.  Here's what I tried:
1. Ensured I was on the latest `master` of both REST API and Angular
2. Started a new Submission, filled out the form.
3. Clicked "Deposit" and the submission saved without errors.

Did I skip a step or do something wrong in reproducing this?

**Comment by atarix83** [comment]
@tdonohue 
I've investigated more on this issue, and the issue is not reproducible with the default workflow configuration, but you can reproduce it using for example the `scoreReview` workflow configuration.
The error with parser has been resolved with https://github.com/DSpace/dspace-angular/pull/624.
Instead the issue with depositing occurs anyway because the server responds with 403 making the request with the full projection option.
I also realize that editing a workflowitem has the same issue without using the default workflow configuration and unfortunately https://github.com/DSpace/dspace-angular/pull/623 doesn't resolve this last problem

**Comment by tdonohue** [comment]
@atarix83 : I'm still not sure how to move it forward.  Submission works for me with the default workflow, and PR #623 doesn't seem to work for the default workflow (see my comments on that PR).  It seems like we either need an update to #623 or another solution.

As a sidenote, is it possible this is related to #581?  I know that the reliance on embedded resources in the Submission/Workflow process has caused issues in the past as well, so I'm wondering if maybe we need to look more closely at how to get the submission/workflow to work better without reliance on embedded content.
